---
require: rubocop-performance

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.*"

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 17.5

Metrics/CyclomaticComplexity:
  Exclude:
    - tip_bot/telegram/request.rb

# RSpec/FilePath:
#   Enabled: false
#
# RSpec/InstanceVariable:
#   Enabled: false
#
# RSpec/VerifiedDoubles:
#   Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
